### ISSUE TITLE
Compilation error when using JUCE 5.4.4

### ISSUE THREAD

**Issue by franklange** [McMartin/FRUT#510]
Hi,
currently FRUT doesn't seem to compile with JUCE 5.4.4.
The issue seems to be that JUCE switched from using its own `juce::ScopedPointer` to using the STL's `std::unique_ptr`. Unfortunately this means that the return type of a couple of JUCE functions have changed and now cause compilation errors when building the tools provided by FRUT.

**Comment by McMartin** [comment]
Hi @franklange,

Thank you very much for creating this issue and reporting that problem. I opened https://github.com/McMartin/FRUT/pull/511 to fix it. Sorry for the inconvenience, I'll try to follow releases of JUCE a bit more closely in the future.
