### PR TITLE
Build with JUCE 5.4.4

### LINKED ISSUE #510: Compilation error when using JUCE 5.4.4
Hi,
currently FRUT doesn't seem to compile with JUCE 5.4.4.
The issue seems to be that JUCE switched from using its own `juce::ScopedPointer` to using the STL's `std::unique_ptr`. Unfortunately this means that the return type of a couple of JUCE functions have changed and now cause compilation errors when building the tools provided by FRUT.

### PR DESCRIPTION
**Pull request by McMartin**
Resolves #510.

@franklange, @MartyLake: please review, thanks!

### CODE REVIEW

**Comment by MartyLake** [comment]
LGTM :D

**Comment by MartyLake** [comment]
LGTM :D

**Comment by franklange** [comment]
:thumbsup:
