### ISSUE TITLE
Undefined symbols for architecture x86_64 when building FRUT on macos 11

### ISSUE THREAD

**Issue by nperreau** [McMartin/FRUT#764]
Hello, I am using FRUT with github actions to build a JUCE project when it is pushed.
However, when compiling Jucer2Cmake on a MacOS 11.7.10 runner with 
```
cmake .. -DCMAKE_INSTALL_PREFIX="../prefix" -DJUCE_ROOT="/Users/runner/work//JUCE"
cmake --build . --target install --parallel
```
I get this linking error:

```
[ 65%] Linking CXX executable BinaryDataBuilder-0.3.1
Undefined symbols for architecture x86_64:
  "_SecCodeCopySelf", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libtools_juce_core.a(juce_core.mm.o)
  "_SecCodeCopySigningInformation", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libtools_juce_core.a(juce_core.mm.o)
  "_kSecCodeInfoEntitlementsDict", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libtools_juce_core.a(juce_core.mm.o)
ld: symbol(s) not found for architecture x86_64
Undefined symbols for architecture x86_64:
  "_SecCodeCopySelf", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libtools_juce_core.a(juce_core.mm.o)
  "_SecCodeCopySigningInformation", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libtools_juce_core.a(juce_core.mm.o)
make[2]: *** [cmake/tools/PListMerger/PListMerger-0.1.0] Error 1
make[1]: *** [cmake/tools/PListMerger/CMakeFiles/PListMerger.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
  "_kSecCodeInfoEntitlementsDict", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libtools_juce_core.a(juce_core.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cmake/tools/BinaryDataBuilder/BinaryDataBuilder-0.3.1] Error 1
make[1]: *** [cmake/tools/BinaryDataBuilder/CMakeFiles/BinaryDataBuilder.dir/all] Error 2
[ 68%] Linking CXX executable Jucer2CMake
Undefined symbols for architecture x86_64:
  "_SecCodeCopySelf", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libJucer2CMake_JUCE.a(juce_core.mm.o)
  "_SecCodeCopySigningInformation", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libJucer2CMake_JUCE.a(juce_core.mm.o)
  "_kSecCodeInfoEntitlementsDict", referenced from:
      juce::SystemStats::isAppSandboxEnabled()::$_23::operator()() const in libJucer2CMake_JUCE.a(juce_core.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Jucer2CMake/Jucer2CMake] Error 1
make[1]: *** [Jucer2CMake/CMakeFiles/Jucer2CMake.dir/all] Error 2
``` 
The C/C++ compiler is `AppleClang 13.0.0.13000029`, and the JUCE and FRUT repositories are cloned in the workflow.

**Comment by McMartin** [comment]
Hi @nperreau
Thank you very much for using FRUT and for opening this issue!
What you discovered is that FRUT doesn't build with JUCE 7.0.6 or newer. I'll working on fixing this as soon as possible, but in the meantime you can workaround this problem by using JUCE 7.0.5.
